[build]
  base = "/build"  
  command = "npm run build" 
  publish = "build"  

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type, x-ms-request-root, x-ms-request-body, x-ms-request-id"

# Environment variables
[build.environment]
  DB_HOST = "nightin.mysql.database.azure.com"
  DB_USER = "ishkhan"
  DB_PASSWORD = "PlatinuM19941!"
  DB_DATABASE = "nightin"
  DB_PORT = "3306"
