[build]
  publish = "build"
  command = "npm run build"

[context.production.environment]
  DB_HOST = "##"
  DB_USER = "##"
  DB_PASSWORD = "##"
  DB_DATABASE = "##"
  DB_PORT = "##"
  DB_CA = "##"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.environment]
  CI = "false"  
